/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MiPedidoRouteImport } from './routes/mi-pedido'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsInstanceNameRouteImport } from './routes/chats.$instanceName'
import { Route as ApiPedidosRouteImport } from './routes/api/pedidos'
import { Route as ApiMiPedidoRouteImport } from './routes/api/mi-pedido'
import { Route as ApiLetraRouteImport } from './routes/api/letra'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiHotmartRouteImport } from './routes/api/hotmart'
import { Route as ApiGeoRouteImport } from './routes/api/geo'
import { Route as ApiWebhookEvolutionRouteImport } from './routes/api/webhook/evolution'
import { Route as ApiCronFollowupsRouteImport } from './routes/api/cron/followups'
import { Route as ApiCronEmailFollowupRouteImport } from './routes/api/cron/email-followup'
import { Route as ApiAgentPauseRouteImport } from './routes/api/agent/pause'

const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPedidoRoute = MiPedidoRouteImport.update({
  id: '/mi-pedido',
  path: '/mi-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsInstanceNameRoute = ChatsInstanceNameRouteImport.update({
  id: '/chats/$instanceName',
  path: '/chats/$instanceName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPedidosRoute = ApiPedidosRouteImport.update({
  id: '/api/pedidos',
  path: '/api/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMiPedidoRoute = ApiMiPedidoRouteImport.update({
  id: '/api/mi-pedido',
  path: '/api/mi-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLetraRoute = ApiLetraRouteImport.update({
  id: '/api/letra',
  path: '/api/letra',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotmartRoute = ApiHotmartRouteImport.update({
  id: '/api/hotmart',
  path: '/api/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoRoute = ApiGeoRouteImport.update({
  id: '/api/geo',
  path: '/api/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookEvolutionRoute = ApiWebhookEvolutionRouteImport.update({
  id: '/api/webhook/evolution',
  path: '/api/webhook/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFollowupsRoute = ApiCronFollowupsRouteImport.update({
  id: '/api/cron/followups',
  path: '/api/cron/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronEmailFollowupRoute = ApiCronEmailFollowupRouteImport.update({
  id: '/api/cron/email-followup',
  path: '/api/cron/email-followup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPauseRoute = ApiAgentPauseRouteImport.update({
  id: '/api/agent/pause',
  path: '/api/agent/pause',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/follow-up': typeof FollowUpRoute
  '/mi-pedido': typeof MiPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/api/geo': typeof ApiGeoRoute
  '/api/hotmart': typeof ApiHotmartRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/letra': typeof ApiLetraRoute
  '/api/mi-pedido': typeof ApiMiPedidoRoute
  '/api/pedidos': typeof ApiPedidosRoute
  '/chats/$instanceName': typeof ChatsInstanceNameRoute
  '/api/agent/pause': typeof ApiAgentPauseRoute
  '/api/cron/email-followup': typeof ApiCronEmailFollowupRoute
  '/api/cron/followups': typeof ApiCronFollowupsRoute
  '/api/webhook/evolution': typeof ApiWebhookEvolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/follow-up': typeof FollowUpRoute
  '/mi-pedido': typeof MiPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/api/geo': typeof ApiGeoRoute
  '/api/hotmart': typeof ApiHotmartRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/letra': typeof ApiLetraRoute
  '/api/mi-pedido': typeof ApiMiPedidoRoute
  '/api/pedidos': typeof ApiPedidosRoute
  '/chats/$instanceName': typeof ChatsInstanceNameRoute
  '/api/agent/pause': typeof ApiAgentPauseRoute
  '/api/cron/email-followup': typeof ApiCronEmailFollowupRoute
  '/api/cron/followups': typeof ApiCronFollowupsRoute
  '/api/webhook/evolution': typeof ApiWebhookEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/follow-up': typeof FollowUpRoute
  '/mi-pedido': typeof MiPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/api/geo': typeof ApiGeoRoute
  '/api/hotmart': typeof ApiHotmartRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/letra': typeof ApiLetraRoute
  '/api/mi-pedido': typeof ApiMiPedidoRoute
  '/api/pedidos': typeof ApiPedidosRoute
  '/chats/$instanceName': typeof ChatsInstanceNameRoute
  '/api/agent/pause': typeof ApiAgentPauseRoute
  '/api/cron/email-followup': typeof ApiCronEmailFollowupRoute
  '/api/cron/followups': typeof ApiCronFollowupsRoute
  '/api/webhook/evolution': typeof ApiWebhookEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/follow-up'
    | '/mi-pedido'
    | '/pedidos'
    | '/api/geo'
    | '/api/hotmart'
    | '/api/lead'
    | '/api/leads'
    | '/api/letra'
    | '/api/mi-pedido'
    | '/api/pedidos'
    | '/chats/$instanceName'
    | '/api/agent/pause'
    | '/api/cron/email-followup'
    | '/api/cron/followups'
    | '/api/webhook/evolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/follow-up'
    | '/mi-pedido'
    | '/pedidos'
    | '/api/geo'
    | '/api/hotmart'
    | '/api/lead'
    | '/api/leads'
    | '/api/letra'
    | '/api/mi-pedido'
    | '/api/pedidos'
    | '/chats/$instanceName'
    | '/api/agent/pause'
    | '/api/cron/email-followup'
    | '/api/cron/followups'
    | '/api/webhook/evolution'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/follow-up'
    | '/mi-pedido'
    | '/pedidos'
    | '/api/geo'
    | '/api/hotmart'
    | '/api/lead'
    | '/api/leads'
    | '/api/letra'
    | '/api/mi-pedido'
    | '/api/pedidos'
    | '/chats/$instanceName'
    | '/api/agent/pause'
    | '/api/cron/email-followup'
    | '/api/cron/followups'
    | '/api/webhook/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FollowUpRoute: typeof FollowUpRoute
  MiPedidoRoute: typeof MiPedidoRoute
  PedidosRoute: typeof PedidosRoute
  ApiGeoRoute: typeof ApiGeoRoute
  ApiHotmartRoute: typeof ApiHotmartRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLetraRoute: typeof ApiLetraRoute
  ApiMiPedidoRoute: typeof ApiMiPedidoRoute
  ApiPedidosRoute: typeof ApiPedidosRoute
  ChatsInstanceNameRoute: typeof ChatsInstanceNameRoute
  ApiAgentPauseRoute: typeof ApiAgentPauseRoute
  ApiCronEmailFollowupRoute: typeof ApiCronEmailFollowupRoute
  ApiCronFollowupsRoute: typeof ApiCronFollowupsRoute
  ApiWebhookEvolutionRoute: typeof ApiWebhookEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-pedido': {
      id: '/mi-pedido'
      path: '/mi-pedido'
      fullPath: '/mi-pedido'
      preLoaderRoute: typeof MiPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$instanceName': {
      id: '/chats/$instanceName'
      path: '/chats/$instanceName'
      fullPath: '/chats/$instanceName'
      preLoaderRoute: typeof ChatsInstanceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pedidos': {
      id: '/api/pedidos'
      path: '/api/pedidos'
      fullPath: '/api/pedidos'
      preLoaderRoute: typeof ApiPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mi-pedido': {
      id: '/api/mi-pedido'
      path: '/api/mi-pedido'
      fullPath: '/api/mi-pedido'
      preLoaderRoute: typeof ApiMiPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/letra': {
      id: '/api/letra'
      path: '/api/letra'
      fullPath: '/api/letra'
      preLoaderRoute: typeof ApiLetraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotmart': {
      id: '/api/hotmart'
      path: '/api/hotmart'
      fullPath: '/api/hotmart'
      preLoaderRoute: typeof ApiHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo': {
      id: '/api/geo'
      path: '/api/geo'
      fullPath: '/api/geo'
      preLoaderRoute: typeof ApiGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/evolution': {
      id: '/api/webhook/evolution'
      path: '/api/webhook/evolution'
      fullPath: '/api/webhook/evolution'
      preLoaderRoute: typeof ApiWebhookEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/followups': {
      id: '/api/cron/followups'
      path: '/api/cron/followups'
      fullPath: '/api/cron/followups'
      preLoaderRoute: typeof ApiCronFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/email-followup': {
      id: '/api/cron/email-followup'
      path: '/api/cron/email-followup'
      fullPath: '/api/cron/email-followup'
      preLoaderRoute: typeof ApiCronEmailFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/pause': {
      id: '/api/agent/pause'
      path: '/api/agent/pause'
      fullPath: '/api/agent/pause'
      preLoaderRoute: typeof ApiAgentPauseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FollowUpRoute: FollowUpRoute,
  MiPedidoRoute: MiPedidoRoute,
  PedidosRoute: PedidosRoute,
  ApiGeoRoute: ApiGeoRoute,
  ApiHotmartRoute: ApiHotmartRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLetraRoute: ApiLetraRoute,
  ApiMiPedidoRoute: ApiMiPedidoRoute,
  ApiPedidosRoute: ApiPedidosRoute,
  ChatsInstanceNameRoute: ChatsInstanceNameRoute,
  ApiAgentPauseRoute: ApiAgentPauseRoute,
  ApiCronEmailFollowupRoute: ApiCronEmailFollowupRoute,
  ApiCronFollowupsRoute: ApiCronFollowupsRoute,
  ApiWebhookEvolutionRoute: ApiWebhookEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
