/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsInstanceNameRouteImport } from './routes/chats.$instanceName'
import { Route as ApiWebhookEvolutionRouteImport } from './routes/api/webhook/evolution'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsInstanceNameRoute = ChatsInstanceNameRouteImport.update({
  id: '/chats/$instanceName',
  path: '/chats/$instanceName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookEvolutionRoute = ApiWebhookEvolutionRouteImport.update({
  id: '/api/webhook/evolution',
  path: '/api/webhook/evolution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats/$instanceName': typeof ChatsInstanceNameRoute
  '/api/webhook/evolution': typeof ApiWebhookEvolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats/$instanceName': typeof ChatsInstanceNameRoute
  '/api/webhook/evolution': typeof ApiWebhookEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats/$instanceName': typeof ChatsInstanceNameRoute
  '/api/webhook/evolution': typeof ApiWebhookEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats/$instanceName' | '/api/webhook/evolution'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats/$instanceName' | '/api/webhook/evolution'
  id: '__root__' | '/' | '/chats/$instanceName' | '/api/webhook/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsInstanceNameRoute: typeof ChatsInstanceNameRoute
  ApiWebhookEvolutionRoute: typeof ApiWebhookEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$instanceName': {
      id: '/chats/$instanceName'
      path: '/chats/$instanceName'
      fullPath: '/chats/$instanceName'
      preLoaderRoute: typeof ChatsInstanceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/evolution': {
      id: '/api/webhook/evolution'
      path: '/api/webhook/evolution'
      fullPath: '/api/webhook/evolution'
      preLoaderRoute: typeof ApiWebhookEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsInstanceNameRoute: ChatsInstanceNameRoute,
  ApiWebhookEvolutionRoute: ApiWebhookEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
